# Generated by Django 4.0.10 on 2024-08-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_question_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
    ]
